### ISSUE TITLE
preprocessing_surf.py Value Error: Expected 2D array, got 1D array instead

### ISSUE THREAD

**Issue by vamas2** [imRishabhGupta/Indian-Sign-Language-Recognition#7]
sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
C:\Users\bipin\Anaconda3\lib\site-packages\sklearn\grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)
Train-test-val split: 0 training rows, 0 test rows, 0 validation rows
0 descriptors before clustering
Using clustering model MiniBatchKMeans(batch_size=100, compute_labels=True, init='k-means++',
        init_size=None, max_iter=100, max_no_improvement=10,
        n_clusters=150, n_init=3, random_state=None,
        reassignment_ratio=0.01, tol=0.0, verbose=0)...
Clustering on training set to get codebook of 150 words
Traceback (most recent call last):
  File "preprocessing_surf.py", line 204, in <module>
    X, cluster_model = cluster_features(img_descs, training_idxs, MiniBatchKMeans(n_clusters=150))
  File "preprocessing_surf.py", line 120, in cluster_features
    cluster_model.fit(all_train_descriptors)
  File "C:\Users\bipin\Anaconda3\lib\site-packages\sklearn\cluster\k_means_.py", line 1354, in fit
    dtype=[np.float64, np.float32])
  File "C:\Users\bipin\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 441, in check_array
    "if it contains a single sample.".format(array))
ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

**This is the error I get when I try to run preprocessing_surf.py. How do I solve this error?**

**Comment by yashsinojiya1898** [comment]
Put the train folder in the same folder with four files mentioned..

**Comment by vamas2** [comment]
@yashsinojiya1898 i have. but it says that the array must be non-empty

**Comment by ashok2811** [comment]
use '/ ' instead of '\\' and '\\\\' .

**Comment by yashsinojiya1898** [comment]
Thank you for replying..😀

**Comment by Amchuz** [comment]
@yashsinojiya1898 The folder, did you mean in sklearn ?
I am facing the same error right now.

**Comment by yashsinojiya1898** [comment]
> @yashsinojiya1898 The folder, did you mean in sklearn ?
> I am facing the same error right now.

No, put it in the same folder where your code files are.

**Comment by Amchuz** [comment]
@yashsinojiya1898 Thanks for the reply.
I have put it in the same folder but its not working.

**Comment by bhanu-1902** [comment]
I am facing the same problem..any solutions @yashsinojiya1898

**Comment by snehanals14** [comment]
> 

is your problem solved?
if yes can you tell me how did you do it?
